### ISSUE TITLE
Bugs what i have discovered so far

### ISSUE THREAD

**Issue by Bartixxx32** [tgbot-collection/ytdlbot#57] opened 2022-02-08 19:47 UTC
- [x] #59

- [x] Seems the codec for 4k video (which is default high quality) even struggless on flagship phone. `Oneplus 7Pro`

**Idea to reslove:**
- Find other way to resolve the issue or `V`
  - Change way to pick resolution in /settings from `High/Mid/Low` to > `(highest avalible) / 1080 / 720 / 480 / 360` to make user more control on resolution he is searching

- [ ]  Bot seems treating all youtube shorts as one, steps to reproduce
   1. Send bot youtube short with `/shorts/` in url
   2. let bot send downloaded short
   3. send other short from youtube, and if bug was reproduced successfully, bot should resend old short from step `II.`

- [x] The `convert to audio` Inline button do not appear on videos forwarded from `ARCHIVE` channel
**Idea to reslove:**
- I dont know if its possible to add inline button to arleady existing and forwarded message, but if not add workaround to it by adding clickable LINK(command) inside the message for example

-------------------------------------

Video Name.mp4

https://youtu.be/examplevideo

Info: 854x480 4.9MiB 125s

Downloaded by Unknown

Click to convert: [clickme](clickme)

-------------------------------------

**Comment by BennyThink** [comment] 2022-02-09 02:29
1. 4K video: VLC works fine for me in PC and Phone. Telegram client lacks the ability to decode and play it. That's one irrelevant story for this project. won't fix.
2. detail resolution selection: this will make the code more complicated...that might happen in the future. Open another issue to have it tracked.
3. Can't reproduce issue with `/shorts/`
4. Indented by Telegram forwarding mechanism. Telegram private message doesn't have a link. Group and channel have link but they could be private so external users can't view the origin message. won't fix.

**Closed** 2022-02-09 05:54 UTC
Labels: bug, wontfix
